# Generated by Django 6.0.3 on 2026-04-25 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnoza",
            options={"verbose_name": "Diagnoza", "verbose_name_plural": "Diagnozy"},
        ),
        migrations.AlterModelOptions(
            name="magazyn",
            options={
                "verbose_name": "Operacja magazynowa",
                "verbose_name_plural": "Magazyn",
            },
        ),
        migrations.AlterModelOptions(
            name="platnosc",
            options={"verbose_name": "Płatność", "verbose_name_plural": "Płatności"},
        ),
        migrations.AlterModelOptions(
            name="powiadomienie",
            options={
                "verbose_name": "Powiadomienie",
                "verbose_name_plural": "Powiadomienia",
            },
        ),
        migrations.AlterModelOptions(
            name="raportnaprawy",
            options={
                "verbose_name": "Raport naprawy",
                "verbose_name_plural": "Raporty napraw",
            },
        ),
        migrations.AlterModelOptions(
            name="zuzytaczesc",
            options={
                "verbose_name": "Zużyta część",
                "verbose_name_plural": "Zużyte części",
            },
        ),
    ]
