# Generated by Django 6.0.3 on 2026-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0005_add_database_routines"),
    ]

    operations = [
        migrations.AddField(
            model_name="powiadomienie",
            name="czy_odczytane",
            field=models.BooleanField(default=False),
        ),
    ]
