# Generated by Django 6.0.3 on 2026-03-21 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Czesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("stan_magazynowy", models.IntegerField(default=0)),
                ("stan_minimalny", models.IntegerField(default=0)),
                ("cena", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["nazwa"],
            },
        ),
        migrations.CreateModel(
            name="Uzytkownik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imie", models.CharField(max_length=50)),
                ("nazwisko", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("haslo", models.CharField(max_length=255)),
                (
                    "rola",
                    models.CharField(
                        choices=[
                            ("klient", "Klient"),
                            ("mechanik", "Mechanik"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["nazwisko", "imie"],
            },
        ),
        migrations.CreateModel(
            name="Magazyn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilosc", models.IntegerField()),
                (
                    "typ_operacji",
                    models.CharField(
                        choices=[("przyjecie", "Przyjęcie"), ("wydanie", "Wydanie")],
                        max_length=20,
                    ),
                ),
                ("data_operacji", models.DateTimeField(auto_now_add=True)),
                (
                    "czesc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operacje_magazynowe",
                        to="app.czesc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marka", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("typ", models.CharField(max_length=50)),
                ("numer_seryjny", models.CharField(max_length=100, unique=True)),
                (
                    "klient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rowery",
                        to="app.uzytkownik",
                    ),
                ),
            ],
            options={
                "ordering": ["marka", "model"],
            },
        ),
        migrations.CreateModel(
            name="Zgloszenie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zgloszenia", models.DateTimeField(auto_now_add=True)),
                ("opis_usterki", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nowe", "Nowe"),
                            ("w_trakcie", "W trakcie"),
                            ("zakonczone", "Zakończone"),
                        ],
                        default="nowe",
                        max_length=30,
                    ),
                ),
                (
                    "klient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zgloszenia",
                        to="app.uzytkownik",
                    ),
                ),
                (
                    "rower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zgloszenia",
                        to="app.rower",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_zgloszenia"],
            },
        ),
        migrations.CreateModel(
            name="ZlecenieSerwisowe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_przyjecia", models.DateTimeField(auto_now_add=True)),
                ("data_zakonczenia", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("przyjete", "Przyjęte"),
                            ("diagnoza", "Diagnoza"),
                            ("naprawa", "Naprawa"),
                            ("gotowe", "Gotowe"),
                            ("wydane", "Wydane"),
                        ],
                        default="przyjete",
                        max_length=30,
                    ),
                ),
                (
                    "mechanik",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zlecenia_mechanika",
                        to="app.uzytkownik",
                    ),
                ),
                (
                    "zgloszenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zlecenia",
                        to="app.zgloszenie",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_przyjecia"],
            },
        ),
        migrations.CreateModel(
            name="RaportNaprawy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_czynnosci", models.TextField()),
                ("data_raportu", models.DateTimeField(auto_now_add=True)),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raporty",
                        to="app.zlecenieserwisowe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Powiadomienie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tresc", models.TextField()),
                ("data_wyslania", models.DateTimeField(auto_now_add=True)),
                (
                    "uzytkownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powiadomienia",
                        to="app.uzytkownik",
                    ),
                ),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powiadomienia",
                        to="app.zlecenieserwisowe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Platnosc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kwota", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_platnosci", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("oczekuje", "Oczekuje"),
                            ("oplacona", "Opłacona"),
                            ("anulowana", "Anulowana"),
                        ],
                        default="oczekuje",
                        max_length=20,
                    ),
                ),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platnosci",
                        to="app.zlecenieserwisowe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diagnoza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opis_diagnozy", models.TextField()),
                ("data_diagnozy", models.DateTimeField(auto_now_add=True)),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnozy",
                        to="app.zlecenieserwisowe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZuzytaCzesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilosc", models.IntegerField(default=1)),
                (
                    "czesc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zuzycia",
                        to="app.czesc",
                    ),
                ),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zuzyte_czesci",
                        to="app.zlecenieserwisowe",
                    ),
                ),
            ],
        ),
    ]
